### ISSUE TITLE
Module 01 Lesson 01 (von Thünen)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#20]
**Describe the issue**
There's a typo in von Thünen's year of birth, it should be 1783 (see https://en.wikipedia.org/wiki/Johann_Heinrich_von_Th%C3%BCnen)

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 01 -> Section 1.4.1

**Screenshots**
![imagen](https://github.com/UNIGIS-Salzburg/UNIGIS_issue_tracker/assets/58012611/46627139-e580-4b6f-946b-8c3ad621ffd3)

**Comment by kwoehs** [comment]
fixed 08.02.2024 by Katharina Wöhs
