### ISSUE TITLE
Module 01 Lesson 04 (latitude figure)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#21]
**Describe the issue**
Figures 4.5 and 4.6 are too small in the PDF version of module materials. This doesn't happen in the web version.

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 04 -> Sections 4.5.1 and 4.5.2

**Screenshots**
![02](https://github.com/UNIGIS-Salzburg/UNIGIS_issue_tracker/assets/58012611/7985e7ec-747a-41be-bd52-f24407dff540)

**Further information**
Since the Bookdown format is being used, I suggest to apply the `out.width` or `out.height` chunk options (see https://yihui.org/knitr/options/#plots).

**Comment by kwoehs** [comment]
Issue closed by KW on 12 Feb 2024
