### ISSUE TITLE
Module 01 Lesson 05 (datum transformation)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#22]
**Describe the issue**
In a paragraph that explains datum transformations, it is written "e.g., from ETRS89 by MGI" where it should be "e.g., from ETRS89 **to** MGI". Also, below it is written "i.e., after ETRS89 MGI" which isn't clear.

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 05 -> before Figure 5.1

**Screenshots**
![imagen](https://github.com/UNIGIS-Salzburg/UNIGIS_issue_tracker/assets/58012611/92b44f82-915c-463a-8fb8-6ca5c865baab)

**Comment by kwoehs** [comment]
closed by KW on 12 Feb 2024
