### ISSUE TITLE
Module 01 Lesson 08 (Royal Society)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#23]
**Describe the issue**
When referencing the Royal Geographical Society, the citation appears like "(Society 2020)". Then, in the references list, it appears like "Society, Royal Geographical. 2020".

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 08 -> before Figure 8.1

**Screenshots**
![imagen](https://github.com/UNIGIS-Salzburg/UNIGIS_issue_tracker/assets/58012611/6d3ecce7-d9a7-4bd8-8250-2e5b3442350a)

**Further information**
In my experience, this issue can be solved by replacing: `author = "Royal Geographical Society"`
with: `author = {{Royal Geographical Society}}`
in the `.bib` file.

**Comment by karnassioti** [comment]
issue  Module 01 Lesson 08 (Royal Society) #23  closed :)
