### ISSUE TITLE
Module 01 Lesson 08 (Geoinformatics in a social context)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#24]
**Describe the issue**
There's a paragraph that reads "The image on the left shows the land of natives before and after urban development occurred in the place. The map on the right shows (...)", however the mentioned images aren't available.

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 08 -> Section 8.3

**Comment by kwoehs** [comment]
closed by KW on 14.02.2024
