### ISSUE TITLE
Module 01 Lesson 11 (data collection)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#25]
**Describe the issue**
Where it is written "we are no confronted" it seems like it should be "we are **now** confronted".

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 11 -> after Figure 11.3

**Screenshots**
![imagen](https://github.com/UNIGIS-Salzburg/UNIGIS_issue_tracker/assets/58012611/73dcb343-c425-4c44-aad9-2f966a66fb89)

**Comment by kwoehs** [comment]
closed by KW Feb 2024
