### ISSUE TITLE
Module 01 Lesson 13 (Sheppard)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#26]
**Describe the issue**
Where it is written "In the mid 90’s Eric Sheppard wrote (...)" the link to Sheppard's profile is broken.

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 13 -> before Section 13.1

**Comment by kwoehs** [comment]
closed by KW in Feb 2024
