### ISSUE TITLE
Module 01 Lesson 13 (Code of Ethics)

### ISSUE THREAD

**Issue by ruevko** [gwallentin/UNIGIS_SpatSim_issues#27]
**Describe the issue**
Where it is written "(URISA) has issued a GIS Code of Ethics in 2003" the link to the Code is broken. This happens again below, where it is written "'Code of Ethics' for Geoinformatics".

**Where is the issue located?**
Module 01 (Introduction to Geoinformatics) -> Lesson 13 -> before Section 13.4

**Further information**
It seems like this resource has been moved here: https://urisa.org/resource/resmgr/documents/admin/codeofethics.pdf

**Comment by kwoehs** [comment]
closed KW
